version: '3.8'

services:
  app:
    image: node:18
    container_name: node_app
    ports:
      - "3002:3002"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      - PORT=3002
      - API_KEY=${API_KEY}
      - FRONT_URL=${FRONT_URL}
    command: bash -c "npm install && node index.js"
